export const CANONICAL_TAGS = [
  'Angular',
  'ATS',
  'Benefits',
  'Boolean search',
  'Change',
  'Coaching',
  'Collaboration',
  'Compliance',
  'Content',
  'CRM',
  'Culture',
  'Events',
  'Excel',
  'Figma',
  'Full-cycle',
  'Growth',
  'HRIS',
  'Interviews',
  'LinkedIn',
  'Onboarding',
  'Outbound',
  'Payroll',
  'People programs',
  'People-first',
  'Pipeline',
  'Prototyping',
  'Prospecting',
  'Reporting',
  'Screening',
  'Social media',
  'Sourcing',
  'Stakeholder mgmt',
  'Surveys',
  'TypeScript',
  'UI',
  'UX Research'
] as const;
